config/routes.rb
SignsOfHope::Application.routes.draw do

  resources :visitors

  get "visitor/edit"

  get "visitor/index"

  get "visitor/new"

  get "visitor/show"

  get "notifications/index"

  get "notifications/create"

  root to: "welcome#index"

  get "welcome/about"

  get "welcome/programs"

  get "welcome/events"

  get "welcome/sponsors"

  get "welcome/how"

  get "welcome/contact"

  get "welcome/breakfast"

  get "welcome/family"

  get "welcome/classroom"

  get "welcome/school"

  get "welcome/gift"

  get "welcome/bicycle"

  get "welcome/sign"

  get "welcome/eye"

end

app/models/visitor.rb
class Visitor < ActiveRecord::Base
  attr_accessible :email, :message, :name, :phone

  validates :name, presence: true
  validates :email, presence: true
  validates :phone, presence: true
  validates :message, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  def index
  end

  def show
    @visitor = Visitor.find(params[:id])
  end

  def new
    @visitor = Visitor.new
  end

  def create
    @visitor = Visitor.new(params[:visitor])
    if @visitor.save
      UserEmail.signup_notify(@visitor).deliver
      flash[:notice] = "Thank you for your enquiry. We will contact you shortly."
      redirect_to @visitor
    else
      flash[:error] = "There was an error with your enquiry. Please ask again."
      render :new
    end
  end

  def edit
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end

  def programs
  end

  def events
  end

  def sponsors
  end

  def how
  end

  def contact
  end

  def breakfast
  end

  def family
  end

  def classroom
  end

  def school
  end

  def gift
  end

  def bicycle
  end

  def sign
  end

  def eye
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/helpers/visitor_helper.rb
module VisitorHelper
end

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <!--[if IE8]>
  <meta http-equiv=”X-UA-Compatible” content=”IE=EmulateIE10″ /><![endif]-->
<!--[if IE]><script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script><![endif]-->
  <title>SignsOfHope</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <link rel="stylesheet" href="slimmenu.css" type="text/css">

  <link href="/stylesheets/screen.css" media="screen, projection" rel="stylesheet" type="text/css" />
  <link href="/stylesheets/print.css" media="print" rel="stylesheet" type="text/css" />
  <!--[if IE]>
      <link href="/stylesheets/ie.css" media="screen, projection" rel="stylesheet" type="text/css" />
  <![endif]-->
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">

  <script type="text/javascript">
  $(document).ready(function() {
  $("a.fancybox-button").fancybox({
    prevEffect    : 'none',
    nextEffect    : 'none',
    closeBtn    : true,
    helpers   : {
      title : { type : 'inside' },
      buttons : {}
    }
  });
});
</script>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-48944910-1', 'signsofhopeinafrica.herokuapp.com');
  ga('send', 'pageview');

</script>
</head>
<body>
  <header>
    <div class="slimmenu">
        <ul id="navigation" class="slimmenu">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "About Us", welcome_about_path %></li>
          <li><%= link_to "Programs", "#" %>
            <ul>
              <li><%= link_to "Breakfast Program", welcome_breakfast_path %></li>
              <li><%= link_to "Family Sponsorship", welcome_family_path %></li>
              <li><%= link_to "Classroom Project", welcome_classroom_path %></li>
              <li><%= link_to "School Uniform", welcome_school_path %></li>
              <li><%= link_to "Gift of Giving", welcome_gift_path %></li>
              <li><%= link_to "Bicycle Program", welcome_bicycle_path %></li>
              <li><%= link_to "Sign Language Program", welcome_sign_path %></li>
              <li><%= link_to "Eye Clinic", welcome_eye_path %></li>
            </ul>
          </li>
          <li><%= link_to "Events", welcome_events_path %></li>
          <li><%= link_to "Sponsors", welcome_sponsors_path %></li>
          <li><%= link_to "How You Can Help", welcome_how_path %></li>
          <li><%= link_to "Contact Us", new_visitor_path %></li>
        </ul>
    </div>
  </header>

  <%= yield %>
  <footer>
    <section class="layout">
      <div class="socialmediaicons"><span class="title"></span>
        <ul>
          <li><a href="http://linkedin.com" target="_blank"><%= image_tag("linkedin.png") %></a></li>
          <li><a href="http://twitter.com" target="_blank"><%= image_tag("twitter.png") %></a></li>
          <li><a href="https://www.facebook.com/SignsOfHopeInAfrica" target="_blank"><%= image_tag("facebook.jpeg") %></a></li>
          <li><a href="http://youtube.com" target="_blank"><%= image_tag("youtube.png") %></a></li>
          <li class="donate"><a href="https://www.canadahelps.org/CharityProfilePage.aspx?CharityID=s100792" target="_blank"><%= image_tag("Donate_Now.jpg") %></a></li>
        </ul>
        <br>
        <br>
        <br>
        <br>
        <div class="difference">
        <h3>Together We CAN Make A Difference</h3>
        <br>
        <p>Signs Of Hope In Africa &copy 2013</p>
      </div>
      </div>
    </section>
  </footer>
  <script src="jquery.slimmenu.min.js"></script>
  <script type="text/javascript">
    $('#navigation').slimmenu(
{
    resizeWidth: '800',
    collapserTitle: 'Signs of Hope in Africa',
    animSpeed: 'medium',
    easingEffect: null,
    indentChildren: false,
    childrenIndenter: '&nbsp;'
});
  </script>
</body>
</html>

app/views/user_email/signup_notify.html.erb
<p>Hello <%= @visitor.name %>,</p>

<p>Thank you for your enquiry. We are excited you have taken the time to consider our charity!</p>

<p>Here is a summary of your enquiry:</P>

<p>Name:&nbsp;&nbsp; <%= @visitor.name %></p>

<p>Email:&nbsp;&nbsp; <%= @visitor.email %></p>

<p>Telephone:&nbsp;&nbsp; <%= @visitor.phone %></p>

<p>Enquiry:&nbsp;&nbsp; <%= @visitor.message %></p>



<p>We will contact you shortly to discuss your requirements.</p>

<p>Sincerely,</p>

<p>Kristi Falconer</p>

app/views/user_email/signup_notify.text.erb
Hello <%= @visitor.name %>,

Thank you for your enquiry. We are excited you have taken the time to considre our charity!

We will aim to get back to you within the next 24 hours, but please feel free to browse our website in the meantime.

Sincerely,

Kristi Falconer

app/views/visitors/edit.html.erb
<h1>Visitors#edit</h1>
<p>Find me in app/views/visitors/edit.html.erb</p>

app/views/visitors/index.html.erb
<h1>Visitors#index</h1>
<p>Find me in app/views/visitors/index.html.erb</p>

app/views/visitors/new.html.erb
<div class="hero">
  <section class="layout">
    <div class="branding"><%= image_tag("header_image_1.jpg") %></div>
  </section>
</div>

<div class="page-title">
  <section class="layout">
    <h1>Contact Us<a href="https://www.canadahelps.org/CharityProfilePage.aspx?CharityID=s100792" target="_blank"><%= image_tag("Donate_Now.jpg") %></a></h1>
  </section>
</div>

<div class="contact-page-layout">
  <div class="page-text">
    <p>Signs of Hope in Africa
      <br>
      433-1575 Begbie Street, Victoria, BC Canada, V8R 1L2
      <br>Email: info@signsofhopeinafrica.org
      <br>Tel: 250-514-9192</p>
  </div>
</div>
<br>
<br>

<div class="contact-page-layout">
  <section>
<div class="contact-image">
  <section class="layout">
    <div class="branding"><%= image_tag("contact_image.jpg") %></div>
  </section>
</div>

<div class="program-page-layout">
  <section="layout">
    <%= simple_form_for @visitor, :html => { :class => "simple-form"} do |f| %>
      <div class="simple-form">
        <%= f.input :name, :input_html => { style: 'width: 280px; '}, label: false, placeholder: 'Name' %>
      </div>
      <div>
        <div>
          <%= f.input :email, :input_html => { style: 'width: 280px; '}, label: false, placeholder: 'Email' %>
        </div>
      <div>
        <%= f.input :phone, :input_html => { style: 'width: 280px; '}, label: false, placeholder: 'Telephone No.' %>
      </div>
      <div>
        <%= f.input :message,as: :text, :input_html => { style: 'height: 80px; width: 280px; '}, label: false, placeholder: 'Enquiry'%>
      </div>
      <div>
        <%= f.submit "Submit", :class => "create" %>
      </div>
      <div>
      <% end %>
    </div>
  </div>
</section>
</div>
</section>
<div>

app/views/visitors/show.html.erb
<div class="hero">
  <section class="layout">
    <div class="branding"><%= image_tag("header_image_1.jpg") %></div>
  </section>
</div>

<div class="page-title">
  <section class="layout">
    <h1>Thank You<a href="https://www.canadahelps.org/CharityProfilePage.aspx?CharityID=s100792" target="_blank"><%= image_tag("Donate_Now.jpg") %></a></h1>
  </section>
</div>

<div class="contact-page-layout">
  <div class="page-text">
    <p>Signs of Hope in Africa
      <br>
      433-1575 Begbie Street, Victoria, BC Canada, V8R 1L2
      <br>Email: info@signsofhopeinafrica.org
      <br>Tel: 250-514-9192</p>
  </div>
</div>
<br>
<br>

<div class="contact-page-layout">
<div class="contact-image">
  <section class="layout">
    <div class="branding"><%= image_tag("contact_image.jpg") %></div>
  </section>
</div>

	<section="layout">
<div class="page-title">
  	<br>
			<p>Hello <%= @visitor.name %>,
			<br>
			<br>
			Thank you for your enquiry.
			<br>
			<br>
			We will be in touch with you shortly.
			<br>
			<br>
			Sincerely,
			<br>
			<br>
			Signs Of Hope In Africa</p>
	</div>
</section>
</div>

app/views/welcome/about.html.erb
<div class="hero">
  <section class="layout">
    <div class="branding"><%= image_tag("header_image_10.jpg") %></div>
  </section>
</div>

<div class="page-title">
  <section class="layout">
    <h1>About Us<a href="https://www.canadahelps.org/CharityProfilePage.aspx?CharityID=s100792" target="_blank"><%= image_tag("Donate_Now.jpg") %></a></h1>
  </section>
</div>

<div class="boardmembers">
  <section class="layout">
    <div class="about-us">
      <h3><strong>The Start of Many Beginnings</strong></h3>

        <p>In 2003, our founder spent 2 months volunteering in Jambiani, working with Deaf children and teaching English to elders in the village.  It was during this time that Kristi identified key struggles villagers faced in meeting everyday needs.  She quickly realized that some basic projects could provide assistance to meet those needs.
        <br>
        <br>
        Signs of Hope in Africa began to take shape. Projects to meet basic needs expanded into projects that enable villagers to develop economic self-sufficiency using locally available resources.
        <br>
        <br>
        With successful implementation of each project, the quality of life for villagers in Jambiani slowly improves. With improvement comes growth that opens opportunities for the villagers and the community, and spills over to neighbouring regions.
        <br>
        <br>
        Your support is making a positive difference for the lives of many children and their families. We look forward to sharing many more beginnings with you as we continue our work.</p>
        <h3><strong>Our People</strong></h3>

        <p>The board members of Signs of Hope in Africa are all volunteers who passionately invest countless hours to this organization. We also have many dedicated volunteers who donate their time and energy to ensure the success of our fundraisers. The employees we hire from the village to maintain our programs are integral to our progress.
        <br>
        <br>
        We are based in Victoria, British Columbia, Canada. Our key focus in Africa is in the village of Jambiani, Zanzibar, Tanzania
      </p>
      </div><!-- member -->
  	</div>
  </section>
</div>

<div class="board">
    <section class="layout">
      <h1>Board Members</h1>
    </section>
</div>

<div class="boardmembers">
  <section class="layout">
    <div class="members">
      <%= link_to image_tag("kristi.png"), asset_path("kristilarge.png"), class: "fancybox-button", rel: "fancybox-button", title: "Kristi Falconer, President and Founder" %>
      <div class="biography">
        <h3>Kristi Falconer,<span class="small"> President and Founder</span></h3>
        <p>A born and raised Victorian and a registered Sign language interpreter in Victoria since 1992, Kristi has travelled extensively and participated in many community building projects both locally and internationally. She strongly believes that positive role modeling and mentoring of children prepares youth to become future global citizens and humanitarians. She inspires others through her passion, commitment and dedication to Signs of Hope in Africa and she truly believes that, “Together, we CAN make a difference.” Kristi loves spending time outdoors with her young son Kylen.</p>
      </div><!-- member -->
    </div>
  </section>
</div>

 <div class="boardmembers">
  <section class="layout">
    <div class="members">
    	<%= link_to image_tag("tracey.png", class: "img-rounded"), asset_path("traceylarge.png"), class: "fancybox-button", rel: "fancybox-button", title: "Tracey Purvis, Vice-President" %>
      <div class="biography">
        <h3>Tracey Purvis,<span class="small"> Vice-President</span></h3>
        <p>Originally hailing from a small village in Ontario, Tracey lived in Calgary for 10 years before settling in Victoria in 1988. One of her life-long passions is children, running a licensed family daycare for many years while raising her daughter, as well as providing respite foster care. She feels all children deserve an equal start in life and that the futures of the families of Jambiani are already so much brighter thanks to Signs of Hope in Africa. Tracey is currently working in healthcare and in her spare time loves tending her ever-expanding gardens.</p>
      </div>
    </div>
  </section>
</div>

 <div class="boardmembers">
  <section class="layout">
    <div class="members">
    	<%= link_to image_tag("julia.png", class: "img-rounded"), asset_path("julialarge.png"), class: "fancybox-button", rel: "fancybox-button", title: "Julia Keenan, Secretary" %>
      <div class="biography">
        <h3>Julia Keenan,<span class="small"> Secretary</span></h3>
        <p>Growing up in Quebec, Nova Scotia and British Columbia, Julia has a deep appreciation for the opportunities she is privileged to experience as a Canadian. She desires to share her good fortune with vulnerable communities around the world. Since 2005 Julia has worked with students with disabilities at the University of Victoria and has become an advocate for youth education, with special attention to those in different or difficult situations. She has a background in fund development, management, and administration. Julia is an avid baker, hiker, and hockey fan.</p>
      </div><!-- member -->
    </div>
  </section>
</div>

<div class="boardmembers">
  <section class="layout">
    <div class="members">
    	<%= link_to image_tag("ren.png", class: "img-rounded"), asset_path("renlarge.png"), class: "fancybox-button", rel: "fancybox-button", title: "Ren Ashcroft, Treasurer" %>
      <div class="biography">
        <h3>Ren Ashcroft,<span class="small"> Treasurer</span></h3>
        <p>Ren is another true British Columbian, being born in Williams Lake then moving with her family to Vancouver Island in 2001. Currently, she attends Camosun College working toward a Bachelor's Degree in Business with a Major in Accounting. Ren's passion is to make a positive difference in the world by helping those less fortunate than herself. Her belief that all children and families have the right to necessities of life and education is what motivated her to contribute her business and accounting skills to our organization.</p>
      </div><!-- member -->
    </div>
  </section>
 </div>

<div class="boardmembers">
  <section class="layout">
    <div class="members">
    	<%= link_to image_tag("kathy.png", class: "img-rounded"), asset_path("kathylarge.png"), class: "fancybox-button", rel: "fancybox-button", title: "Kathy Martin, Member-at-Large" %>
      <div class="biography">
        <h3>Kathy Martin,<span class="small"> Member-at-large</span></h3>
        <p>Kathy grew up in Mauritius, an island off the east coast of the African continent. After living in UK for 22 years, working in senior management in the healthcare, regulatory and business sectors, she relocated to Victoria with her family. Kathy now has a practice in Victoria working as a Financial Advisor. She has great passion for projects that directly support and impact long term assistance for children and families in Africa. Her aim for the charity is to build business sponsorships and awareness that will make a difference in the future of young people in Jambiani.</p>
      </div><!-- member -->
    </div>
  </section>
</div>

<div class="boardmembers">
  <section class="layout">
    <div class="members">
    	<%= link_to image_tag("mrisho.png"), asset_path("mrisholarge.png"), class: "fancybox-button", rel: "fancybox-button", title: "Mrisho Haji Vuaa, Director" %>
      <div class="biography">
        <h3>Mrisho Haji Vuaa,<span class="small"> Director</span></h3>
        <p>Born and raised on the island of Zanzibar, Mrisho provides a wealth of cultural knowledge and an understanding of the people of Jambiani. He directs project work while mentoring and training families receiving start-up costs in establishing their family businesses. Mrisho has completed training programs in Project Planning Management and Human Resource Management and is a trained HIV/AIDS Educator. Having completed a Hotel and Tourism Program, Mrisho manages a local hotel in Jambiani.</p>
      </div><!-- member -->
    </div>
  </section>
</div>

app/views/welcome/contact.html.erb
<div class="hero">
  <section class="layout">
    <div class="branding"><%= image_tag("header_image_1.jpg") %></div>
  </section>
</div>

<div class="page-title">
	<section class="layout">
		<h1>Contact Us<a href="https://www.canadahelps.org/CharityProfilePage.aspx?CharityID=s100792" target="_blank"><%= image_tag("Donate_Now.jpg") %></a></h1>
	</section>
</div>

app/views/welcome/events.html.erb
<div class="hero">
  <section class="layout">
    <div class="branding"><%= image_tag("header_image_15.jpg") %></div>
  </section>
</div>

<div class="page-title">
  <section class="layout">
    <h1>Events<a href="https://www.canadahelps.org/CharityProfilePage.aspx?CharityID=s100792" target="_blank"><%= image_tag("Donate_Now.jpg") %></a></h1>
  </section>
</div>

<div class="events-page-layout">
<div class="easter-poster">
	<section class="layout">
		<h3>Easter Egg Hunt</h3>
		<%= link_to image_tag("Easter Poster.jpg", class: "img-rounded"), asset_path("Easter Poster.jpg"), class: "fancybox-button", rel: "fancybox-button", title: "" %>
	</section>
</div>

<div class="easter-poster-text">
	<section class="layout">
		<p>Our 5th Annual Easter Egg Hunt at Beckwith Park was a huge success with over 3,200 people in attendance and we raised $7,400. This event included bouncy castles, face painting, crafts, games, police car, fire truck, music, a visit from the Easter Bunny and over 12,000 chocolate eggs. See you on Easter Sunday 2014 at Beckwith Park from 10-1pm.</p>
	</section>
</div>
</section>
</div>

<div class="events-page-layout">
<section class="layout">
<div class="race-poster">
	<section class="layout">
		<h3>Amazing Race For Africa</h3>
		<%= link_to image_tag("Amazing Race 2013-2.jpg", class: "img-rounded"), asset_path("Amazing Race 2013-2.jpg"), class: "fancybox-button", rel: "fancybox-button", title: "" %>
	</section>
</div>

<div class="race-poster-text">
	<section class="layout">
		<p>Round up your team of four and come join us for a day of fun and adventure. 8th Annual Amazing Race for Africa is a timed event with teams deciphering clues, completing tasks and being led to their next destination, task and clue. Prizes to be won!! Ages 14-60+ welcome! Advanced Registration Required $30/person. Click here to Register. Amazing Race Sunday November 3rd 11-4pm at UVic.</p>
	</section>
</div>
</section>
</div>

<div class="race-poster-text">
	<section class="layout">
	<p><strong class="highlighted-text">Please <%= link_to "Contact Us", new_visitor_path %> if you would like to be added to our email list advising of upcoming events.</strong></p>
</section>
</div>

app/views/welcome/how.html.erb
<div class="hero">
  <section class="layout">
    <div class="branding"><%= image_tag("header_image_9.jpg") %></div>
  </section>
</div>

<div class="page-title">
	<section class="layout">
		<h1>How You Can Help<a href="https://www.canadahelps.org/CharityProfilePage.aspx?CharityID=s100792" target="_blank"><%= image_tag("Donate_Now.jpg") %></a></h1>
	</section>
</div>

<div class="how-you-can">
	<section class="layout">
		<h1>Donate</h1>
		<p>Signs of Hope in Africa and the families of Jambiani in which we are supporting, are extremely grateful for your donation. Donations can be made online securely through canadahelps.org
		<br>
		<br>
		<strong class="highlighted-text">Please <%= link_to "Contact Us", new_visitor_path %> if you would like to donate via cheque or money order.</strong></p>
	</section>
</div>

<div class="how-you-can">
	<section class="layout">
		<h1>Gift Of Giving Program</h1>
		<p>Do you want to give a meaningful gift but are on a limited budget? Are you struggling to find a unique gift for someone who “has everything”? Increasingly, many people are choosing to donate to a charity in the name of the gift recipient – truly giving two gifts in one!
		<br>
		<br>
		<strong class="highlighted-text">Details on this innovative idea can be found under <%= link_to "Programs", welcome_gift_path %>.</strong></p>
	</section>
</div>

<div class="how-you-can">
	<section class="layout">
		<h1>Events</h1>
		<p><strong>ATTEND / VOLUNTEER / SPONSOR</strong>
		<br>
		<br>
		<strong>Easter Egg Hunt</strong> - Easter Sunday from 10 am to 1 pm
		<br>
		<br>
		<strong>Amazing Race for Africa</strong> - First Sunday in November 11:30 am to 4:30 pm
		<br>
		<br>
		<strong class="highlighted-text">For event details, please see our <%= link_to "Events", welcome_events_path %> page. To volunteer your services, provide sponsorship, or donate prizes, please email us at info@signsofhopeinafrica.org.</strong></p>
	</section>
</div>

<div class="how-you-can">
	<section class="layout">
		<h1>Fundraiser</h1>
		<p>Holding your own fundraiser is a personally gratifying opportunity easily incorporated into your regular activities or used to teach children how they can make a positive difference for others. Ideas:
		<br>
		<br>
		<strong>‘Half for you and half for me’ birthday party</strong>
		<br>
		<br>
		Your child can invite guests to substitute cash for a gift. Half of the money stays with the birthday child and half comes to Signs of Hope in Africa which will 100% go directly towards supporting children in Jambiani (ie: new uniforms).
		<br>
		<br>
		<strong>Club contributors</strong>
		<br>
		<br>
		Your club or university/corporate/sport team can include a fundraising element in its next event. For example, a garden club can donate all or part of proceeds earned from a community plant sale. A sport/corporate team can challenge other teams to raise more funds than it can in a season. Donate all or part of the proceeds from a BBQ or Beer Garden at a tournament.
		<br>
		<br>
		<strong>Host a Dinner</strong>
		<br>
		<br>
		Invite a group of friends, relatives, colleagues to your place for dinner. Instead of asking them to bring an appy or dessert they can contribute to Sponsoring a Family. Your social evening of dinner with friends will change the future of a family in Jambiani.
		<br>
		<br>
		<strong>Pay-it-Forward</strong>
		<br>
		<br>
		Dedicate winnings from your friendly gaming get-togethers to Signs of Hope in Africa.</p>
	</section>
</div>

<div class="how-you-can">
	<section class="layout">
		<p><strong>Increase Awareness</strong>
			<br>
			<br>
			<strong class="highlighted-text">Please consider adding our website link on your social media (ie: Facebook, Twitter, LinkedIn).</strong>
		</p>
	</section>
</div>

app/views/welcome/index.html.erb
<div>
  <section class="layout">
    <div class="slideshow">
    	<%= image_tag("Signs_of_Hope_in_Africa_1.jpg", class: "active") %>
    	<%= image_tag("Signs_of_Hope_in_Africa_2.jpg") %>
    	<%= image_tag("Signs_of_Hope_in_Africa_3.jpg") %>
    </div>
  </section>
</div>

<div class="program-page-layout">
	<section class="layout">
	<div class="statements">
		  <ul>
		    <li><h1>Our Mission</h1><p>We are a Canadian not-for-profit organization dedicated to improving the quality of life for children and their families living in Jambiani, Tanzania.</p></li>

		    <li><h1>Programs</h1><p>Through sustainable initiatives, we empower villagers to break the cycle of poverty and thrive as a community. Our programs employ and are managed by local villagers.</p></li>

		    <li><h1>Join Us</h1><p>Amazing Race For Africa Sunday November 3rd, 2013 from 11am-4pm. Teams of 4!  <a href="http://www.eventbrite.ca/o/signs-of-hope-in-africa-4658699205?ref=eorgbtn" target="blank">Get registered</a> now to avoid disappointment! Details under <%= link_to "Events", welcome_events_path %>.</li>
		  </ul>
	</div>
</section>
</div>
<script>
	function slideSwitch() {
    var $active = $('.slideshow IMG.active');

    if ( $active.length == 0 ) $active = $('.slideshow IMG:last');

    var $next =  $active.next().length ? $active.next()
        : $('.slideshow IMG:first');

    $active.addClass('last-active');

    $next.css({opacity: 0.0})
        .addClass('active')
        .animate({opacity: 1.0}, 1000, function() {
            $active.removeClass('active last-active');
        });
}

$(function() {
    setInterval( "slideSwitch()", 5000 );
});
</script>